
struct Person {
    _fn: string
    ln: string = "Rabbit"
}

class Helper {
    constructor: function() void {
        console.log("Create a new helper")
    }
    up: function(str string) string {
        return str.toUpperCase()
    }
}

Helper helper = new Helper()

Person x = {
    _fn: "Jojo"
}

array<string> arr = ["test", "1"]
string x2 = 1 + ""
bool y = x2 == ""

/*number x = 1
test
*/number x3 = 1

console.log("test");
