// Code generated by go-bindata.
// sources:
// src/core/_imports.tjs
// src/core/globals.tjs
// src/core/types.tjs
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _srcCore_importsTjs = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xe2\xca\xcc\x2d\xc8\x2f\x2a\x51\x50\x72\x48\xce\x2f\x4a\xd5\x2f\xa9\x2c\x48\x2d\x56\x42\x13\x4c\xcf\xc9\x4f\x4a\xcc\x29\x56\xe2\x02\x04\x00\x00\xff\xff\x33\xa5\x0d\xbf\x2d\x00\x00\x00")

func srcCore_importsTjsBytes() ([]byte, error) {
	return bindataRead(
		_srcCore_importsTjs,
		"src/core/_imports.tjs",
	)
}

func srcCore_importsTjs() (*asset, error) {
	bytes, err := srcCore_importsTjsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "src/core/_imports.tjs", size: 45, mode: os.FileMode(420), modTime: time.Unix(1611781140, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _srcCoreGlobalsTjs = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xe2\x4a\x49\x4d\xcb\xcc\x4b\x55\xc8\xc9\x4f\x4e\xcc\x51\x28\x2e\x29\x2a\x4d\x2e\x51\x88\x4f\xce\xcf\x2b\xce\xcf\x49\x55\xa8\xe6\x52\x50\x50\x50\xc8\xc9\x4f\xb7\x52\x48\x2b\xcd\x4b\xd6\x28\x2e\x29\xca\xcc\x4b\xd7\x54\x28\xcb\xcf\x4c\xe1\xaa\xe5\x82\x69\x86\xab\x87\xd2\x5c\x80\x00\x00\x00\xff\xff\xda\x28\x21\x24\x56\x00\x00\x00")

func srcCoreGlobalsTjsBytes() ([]byte, error) {
	return bindataRead(
		_srcCoreGlobalsTjs,
		"src/core/globals.tjs",
	)
}

func srcCoreGlobalsTjs() (*asset, error) {
	bytes, err := srcCoreGlobalsTjsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "src/core/globals.tjs", size: 86, mode: os.FileMode(420), modTime: time.Unix(1611779290, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _srcCoreTypesTjs = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x52\xed\x4e\xc3\x30\x0c\xfc\xbf\xa7\xf0\x4f\x26\xf5\x09\xa6\x69\xd2\x40\xf0\x0b\x31\x24\xc6\x03\xa4\xa9\xbb\x06\x05\x3b\xca\x07\xea\xb4\xf1\xee\xa8\x49\x5a\xd1\x96\x8a\xfd\xaa\xce\x3e\x9f\xef\xdc\xac\x2a\xac\x15\x21\x38\x6f\x83\xf4\xdd\x47\xd1\xa9\x00\xa9\x85\x73\xf0\x16\x11\x5c\x56\x00\x00\x8a\x2a\x6c\x0f\xf5\x06\xea\x40\xf2\x2e\x11\xd7\x40\xe1\xb3\x44\x1b\x09\xb2\x11\x76\xef\x73\x3f\xd5\xd7\x59\x30\xf6\x35\xd2\xc9\x37\x9b\xdf\x23\xce\x68\xe5\x27\x8a\xc2\x5a\x71\xde\x26\xb4\x4b\xac\x50\x3a\x6f\x47\xc2\x45\x56\xb9\x52\xd0\xfa\x1a\x28\xa5\xa8\x46\xfb\x3c\xbf\x1b\x83\xf6\x41\x38\xcc\xb3\x43\xfb\x7b\x35\xc9\xdd\xab\xa6\xdc\x2f\x11\xe5\xdc\x9e\x1f\x5b\xc3\x84\xe4\x95\xd0\x23\x13\x8b\x7b\x9f\x54\x8b\xd5\x6d\xd4\x67\x96\x42\x63\x3a\xf4\xe8\x10\x93\x64\x05\x70\xf9\x81\xd2\x6f\x05\x9d\x77\x8b\x6a\xaf\x16\xa5\x72\x8a\xe9\xbf\xe5\xb3\x03\x94\xcc\xba\x8f\x7f\xcf\xac\x87\xf0\x23\x6b\xcb\xf3\xf1\xaf\xf5\x02\xfb\x0e\xdc\xfa\x6c\xfe\x78\x16\x26\xb8\x26\x0f\x1c\xd7\xf0\xc5\xaa\x4a\x65\x36\x83\x8f\xe3\xdc\x42\x3a\x50\xef\xe1\x10\x11\x5c\xe6\xbc\x4e\x21\xd6\x7f\x02\x00\x00\xff\xff\x85\x28\xd1\x2e\xfc\x02\x00\x00")

func srcCoreTypesTjsBytes() ([]byte, error) {
	return bindataRead(
		_srcCoreTypesTjs,
		"src/core/types.tjs",
	)
}

func srcCoreTypesTjs() (*asset, error) {
	bytes, err := srcCoreTypesTjsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "src/core/types.tjs", size: 764, mode: os.FileMode(420), modTime: time.Unix(1611008643, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"src/core/_imports.tjs": srcCore_importsTjs,
	"src/core/globals.tjs": srcCoreGlobalsTjs,
	"src/core/types.tjs": srcCoreTypesTjs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"src": &bintree{nil, map[string]*bintree{
		"core": &bintree{nil, map[string]*bintree{
			"_imports.tjs": &bintree{srcCore_importsTjs, map[string]*bintree{}},
			"globals.tjs": &bintree{srcCoreGlobalsTjs, map[string]*bintree{}},
			"types.tjs": &bintree{srcCoreTypesTjs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

