// Code generated by go-bindata.
// sources:
// src/core/types.tjs
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _srcCoreTypesTjs = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x51\x41\x6e\x83\x30\x10\xbc\xfb\x15\x7b\x6c\x24\x5e\x10\x45\x41\x3d\xb4\xa7\xaa\xa9\xd4\x7c\xc0\x18\x13\xb6\x72\x77\x91\xbd\x54\x84\x88\xbf\x57\xb1\x09\x11\x34\xf4\x84\x86\x19\xcf\xce\xce\xaa\xd2\x56\x48\x16\x82\xf8\xd6\xc8\xf5\x83\x74\xca\xc0\x38\x1d\x02\x7c\x46\x04\x17\x05\x00\x80\x54\xda\xee\x50\x6d\xa1\x6a\xc9\x3c\x25\xe1\x06\x90\x24\xb2\xa6\xd6\xfe\x59\x46\x12\x49\x36\xa3\x55\x24\x9d\xa5\x93\xd4\xdb\x49\x1c\x1a\x87\xb2\x30\xd2\xde\xeb\xf3\x2e\xa1\x7d\x52\xb5\x45\x10\x7f\xb7\xcc\xae\xef\xf3\xc9\x78\x50\x8b\xec\xd4\x7e\x17\xd6\xdf\xb2\xbf\x47\x34\x66\x17\x7e\xe9\x1a\x26\x4b\x82\xda\xdd\x1d\xf3\x59\x4a\xe1\x57\xec\x6c\xb9\x4e\xbf\xb1\xd1\xce\xa6\x52\x66\xe9\xf3\x0c\xb8\xf8\xb2\x46\x76\x9a\xce\xfb\xe5\xb3\x0f\x6f\x0d\x06\x64\x7a\xe4\x3c\xa8\xbe\xef\x97\x9b\x14\xcc\x6e\x65\x8f\xd9\xf4\xf5\x2e\x62\x9b\x0f\x2d\xfe\x3f\xe3\xf2\x52\x4d\x1b\xea\x51\x7a\xdc\xc0\x0f\x63\x99\x7e\x73\x33\x45\x38\xfe\x9d\x9e\xca\xb8\x8d\x3f\x44\x04\x17\x35\xa8\xdf\x00\x00\x00\xff\xff\x5e\x70\x36\x82\x6e\x02\x00\x00")

func srcCoreTypesTjsBytes() ([]byte, error) {
	return bindataRead(
		_srcCoreTypesTjs,
		"src/core/types.tjs",
	)
}

func srcCoreTypesTjs() (*asset, error) {
	bytes, err := srcCoreTypesTjsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "src/core/types.tjs", size: 622, mode: os.FileMode(420), modTime: time.Unix(1610563519, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"src/core/types.tjs": srcCoreTypesTjs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"src": &bintree{nil, map[string]*bintree{
		"core": &bintree{nil, map[string]*bintree{
			"types.tjs": &bintree{srcCoreTypesTjs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

