
//#lib "./libs/vue.js"

import App from "./components/app"

App app = new App();

if (true){
    console.log("If")
} else if (1 > 2) {
    console.log("Else if")
} else {
    console.log("Else")
}

while (true) {
    console.log("In a while")
    break;
}

do {
    console.log("In a do while")
    break;
} while (true)

var x = "1";
switch (x) {
    case "1":
    break;
    case "2":
    default: 
    break;
}

for(var i = 0; i < 0; i++) {

}
var list = [1,2,3];
for (var item in list){

}
